version: 0.2

env:
  parameter-store:
     GITHUB_LOGIN : GITHUB_LOGIN
     GITHUB_PASSWORD : GITHUB_PASSWORD
phases:
  build:
    commands:
      - git clone https://$GITHUB_LOGIN:$GITHUB_PASSWORD@github.com/shadow-robot/sr_dexterous_hand_and_arm_documentation.git
      - cd sr_dexterous_hand_and_arm_documentation
      - git submodule init
      - git pull --recurse-submodules
      - cd docs/sr_dexterous_hand_documentation
      - git checkout devel
      - git pull
      - cd ..
      - git add --all
      - if git -c user.name='Devops' -c user.email='devops@shadowrobot.com' commit -m "Automatic updating submodules"; then git push origin devel; fi
      - cd ../../../
      - git clone https://$GITHUB_LOGIN:$GITHUB_PASSWORD@github.com/shadow-robot/sr_dexterous_hand_glove_documentation.git
      - cd sr_dexterous_hand_glove_documentation
      - git submodule init
      - git pull --recurse-submodules
      - cd docs/sr_dexterous_hand_documentation
      - git checkout devel
      - git pull
      - cd ..
      - git add --all
      - if git -c user.name='Devops' -c user.email='devops@shadowrobot.com' commit -m "Automatic updating submodules"; then git push origin devel; fi
